### ISSUE TITLE
Change ModEngine2 Folder?

### ISSUE THREAD

**Issue by Trivaris** [MadTekN1/ERModsMerger#1]
I have Mod Engine set up and installed in ```C:/Program Files/Mod Engine```
So I dropped the ```ERModMerger.exe``` into the same folder as ```config_eldenring.toml```, but when I started the program, I realized that the ```config_eldenring.toml``` of ```.../Mod Engine/ERModsMergerConfig/ModEngine2/config_eldenring.toml``` was being used instead of mine. How can I fix this?

**Comment by MadTekN1** [comment]
Every folders in `ERModsMergerConfig` are extracted (like the ModEngine2) when the first launch is detected and this is a method shared for both the console version (merger only) and the manager version.

And when a config is saved the same kind of shared method will apply modifications to the config of the precedently extracted modengine.

The merger console version is not meant to be used with the integrated modengine inside  `ERModsMergerConfig` nor edit local `config_eldenring.toml` as it's only a "merger". If you want full integrated manager + merger + that do all the config + launch the game for you, use the manager instead.

**Comment by Trivaris** [comment]
I just want it to merge my already existing ModEngine2 mods based on my config file
